name: project_hibiki_point_mobile_app
description: "HIBIKI POINT Mobile App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.6
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  google_sign_in: ^6.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/hibiki_logo_splash.png"
